version: "3"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/mapcreator/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=apj0702
      - POSTGRES_USER=gor
      - POSTGRES_DB=mapcreator
    stop_signal: SIGINT
  web:
    image: us-docker.pkg.dev/greymatter-development/apps/mapcreator:latest
    depends_on:
      - db
    ports:
      - "5000:3001"
  autocad:
    image: map_creator_script:latest
    ports:
      - "3000:3000"
