version: "3"

services:
  mapcreator_db:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/mapcreator/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mapcreator
    stop_signal: SIGINT
  mapcreator-app:
    image: map_creator_app:latest
    depends_on:
      - mapcreator_db
    ports:
      - "5000:3001"
  mapcreator-autocad:
    image: map_creator_script:latest
    ports:
      - "5001:5001"
